# Generated by Django 5.2.1 on 2025-05-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TayinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tercih_adliye', models.CharField(max_length=100)),
                ('talep_turu', models.CharField(choices=[('il_ici', 'İl İçi'), ('il_disi', 'İl Dışı')], max_length=20)),
                ('aciklama', models.TextField(blank=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='requests.personel')),
            ],
        ),
    ]
