# Generated by Django 5.2.1 on 2025-05-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adliye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tayintalebi',
            name='tercih_adliye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests.adliye'),
        ),
    ]
