# Generated by Django 5.2.1 on 2025-05-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_adliye_alter_tayintalebi_tercih_adliye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adliye',
            name='isim',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tayintalebi',
            name='tercih_adliye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.adliye'),
        ),
    ]
